"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import {
  getAgentSchedules,
  updateAgentSchedule,
  deleteAgentSchedule,
  triggerAgentSchedule,
  type AgentSchedule,
} from "@/lib/api";
import { ToastStack, type ToastItem } from "@/app/components/Toast";

function humanizeCron(cron: string): string {
  const parts = cron.trim().split(/\s+/);
  if (parts.length !== 5) return cron;
  const [min, hour, , , dow] = parts;
  const h = parseInt(hour);
  const m = parseInt(min);
  if (isNaN(h) || isNaN(m)) return cron;
  const timeStr = `${h % 12 || 12}:${m.toString().padStart(2, "0")} ${h < 12 ? "AM" : "PM"}`;
  const dayMap: Record<string, string> = {
    "0": "Sunday", "1": "Monday", "2": "Tuesday", "3": "Wednesday",
    "4": "Thursday", "5": "Friday", "6": "Saturday",
  };
  if (dow === "*") return `Every day at ${timeStr} UTC`;
  if (dow === "1-5") return `Weekdays at ${timeStr} UTC`;
  if (dow.includes(",")) {
    const names = dow.split(",").map((d) => dayMap[d] ?? d).join(" & ");
    return `Every ${names} at ${timeStr} UTC`;
  }
  return `Every ${dayMap[dow] ?? `day ${dow}`} at ${timeStr} UTC`;
}

function formatRelative(iso: string | null): string {
  if (!iso) return "—";
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60_000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

function formatNext(iso: string | null): string {
  if (!iso) return "—";
  const diff = new Date(iso).getTime() - Date.now();
  if (diff < 0) return "soon";
  const mins = Math.floor(diff / 60_000);
  if (mins < 60) return `in ${mins}m`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `in ${hrs}h`;
  return `in ${Math.floor(hrs / 24)}d`;
}

const PLATFORM_LABELS: Record<string, string> = {
  linkedin: "LinkedIn",
  twitter: "X / Twitter",
  facebook: "Facebook",
};

export default function AgentSchedulesPage() {
  const [schedules, setSchedules] = useState<AgentSchedule[]>([]);
  const [loading, setLoading] = useState(true);
  const [toasts, setToasts] = useState<ToastItem[]>([]);
  const [triggering, setTriggering] = useState<number | null>(null);
  const [deleting, setDeleting] = useState<number | null>(null);

  const addToast = useCallback((message: string, type: ToastItem["type"]) => {
    setToasts((prev) => [...prev, { id: Date.now(), message, type }]);
  }, []);
  const removeToast = useCallback((id: number) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  }, []);

  useEffect(() => {
    getAgentSchedules()
      .then(setSchedules)
      .catch(() => addToast("Failed to load schedules.", "error"))
      .finally(() => setLoading(false));
  }, [addToast]);

  async function handleToggle(schedule: AgentSchedule) {
    try {
      const updated = await updateAgentSchedule(schedule.id, { is_active: !schedule.is_active });
      setSchedules((prev) => prev.map((s) => (s.id === updated.id ? updated : s)));
    } catch {
      addToast("Failed to update schedule.", "error");
    }
  }

  async function handleTrigger(id: number) {
    setTriggering(id);
    try {
      await triggerAgentSchedule(id);
      addToast("Queued — post will be generated and published shortly.", "success");
    } catch (err) {
      addToast(err instanceof Error ? err.message : "Trigger failed.", "error");
    } finally {
      setTriggering(null);
    }
  }

  async function handleDelete(id: number) {
    setDeleting(id);
    try {
      await deleteAgentSchedule(id);
      setSchedules((prev) => prev.filter((s) => s.id !== id));
      addToast("Schedule deleted.", "success");
    } catch {
      addToast("Failed to delete.", "error");
    } finally {
      setDeleting(null);
    }
  }

  return (
    <div className="max-w-3xl mx-auto px-5 py-8">
      <ToastStack toasts={toasts} onClose={removeToast} />

      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-lg font-semibold text-white">AI Scheduler</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            Recurring posts generated by AI from your topic and template
          </p>
        </div>
        <Link
          href="/dashboard/agent-schedules/new"
          className="flex items-center gap-2 px-4 py-2 bg-[#45b26b] hover:bg-[#3da05f] text-white text-sm font-medium rounded-xl transition-colors"
        >
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
          </svg>
          New schedule
        </Link>
      </div>

      {/* List */}
      {loading ? (
        <div className="flex items-center justify-center py-20">
          <div className="w-5 h-5 border-2 border-[#45b26b]/30 border-t-[#45b26b] rounded-full animate-spin" />
        </div>
      ) : schedules.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <div className="w-12 h-12 rounded-2xl bg-[#1a1a1a] border border-[#2a2a2a] flex items-center justify-center mb-4">
            <svg className="w-6 h-6 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
            </svg>
          </div>
          <p className="text-sm text-gray-400 font-medium">No AI schedules yet</p>
          <p className="text-xs text-gray-600 mt-1 mb-4">
            Set up a recurring topic and let the agent write and publish posts automatically.
          </p>
          <Link
            href="/dashboard/agent-schedules/new"
            className="text-sm text-[#45b26b] hover:underline"
          >
            Create your first schedule
          </Link>
        </div>
      ) : (
        <div className="space-y-3">
          {schedules.map((schedule) => (
            <div
              key={schedule.id}
              className="bg-[#1a1a1a] border border-[#2a2a2a] rounded-xl p-4 flex flex-col gap-3"
            >
              {/* Top row: name + toggle */}
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-white truncate">{schedule.name}</span>
                    <span className={`text-[10px] px-2 py-0.5 rounded-full font-medium ${
                      schedule.is_active
                        ? "bg-[#45b26b]/15 text-[#45b26b]"
                        : "bg-[#2a2a2a] text-gray-500"
                    }`}>
                      {schedule.is_active ? "Active" : "Paused"}
                    </span>
                  </div>
                  <p className="text-xs text-gray-500 mt-1 line-clamp-2">{schedule.description}</p>
                </div>
                {/* Active toggle */}
                <button
                  onClick={() => handleToggle(schedule)}
                  className={`relative flex-shrink-0 w-9 h-5 rounded-full transition-colors ${
                    schedule.is_active ? "bg-[#45b26b]" : "bg-[#2a2a2a]"
                  }`}
                >
                  <span className={`absolute top-0.5 left-0.5 w-4 h-4 rounded-full bg-white transition-transform ${
                    schedule.is_active ? "translate-x-4" : "translate-x-0"
                  }`} />
                </button>
              </div>

              {/* Meta row: platforms + schedule */}
              <div className="flex items-center gap-4 flex-wrap">
                <div className="flex items-center gap-1.5 flex-wrap">
                  {schedule.platforms.map((p) => (
                    <span key={p} className="text-[11px] px-2 py-0.5 bg-[#252525] border border-[#333] rounded-md text-gray-400">
                      {PLATFORM_LABELS[p] ?? p}
                    </span>
                  ))}
                </div>
                <div className="flex items-center gap-1.5 text-xs text-gray-500">
                  <svg className="w-3.5 h-3.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={1.8}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  {humanizeCron(schedule.cron_expression)}
                </div>
              </div>

              {/* Bottom row: last/next run + actions */}
              <div className="flex items-center justify-between pt-1 border-t border-[#252525]">
                <div className="flex items-center gap-4 text-[11px] text-gray-600">
                  <span>Last run: <span className="text-gray-500">{formatRelative(schedule.last_run_at)}</span></span>
                  <span>Next: <span className="text-gray-500">{formatNext(schedule.next_run_at)}</span></span>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleTrigger(schedule.id)}
                    disabled={triggering === schedule.id}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-gray-400 hover:text-white bg-[#252525] hover:bg-[#2f2f2f] border border-[#333] rounded-lg transition-colors disabled:opacity-50"
                  >
                    {triggering === schedule.id ? (
                      <div className="w-3 h-3 border border-gray-500 border-t-white rounded-full animate-spin" />
                    ) : (
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M5.25 5.653c0-.856.917-1.398 1.667-.986l11.54 6.348a1.125 1.125 0 010 1.971l-11.54 6.347a1.125 1.125 0 01-1.667-.985V5.653z" />
                      </svg>
                    )}
                    Run now
                  </button>
                  <button
                    onClick={() => handleDelete(schedule.id)}
                    disabled={deleting === schedule.id}
                    className="p-1.5 text-gray-600 hover:text-red-400 transition-colors disabled:opacity-50"
                    title="Delete schedule"
                  >
                    {deleting === schedule.id ? (
                      <div className="w-3.5 h-3.5 border border-gray-600 border-t-red-400 rounded-full animate-spin" />
                    ) : (
                      <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                      </svg>
                    )}
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
